/*
  # Create books table for Reading Realm

  1. New Tables
    - `books`
      - `id` (text, primary key) - Using string IDs as generated by the app
      - `title` (text, required)
      - `author` (text, required)
      - `completionMonth` (integer, required)
      - `completionYear` (integer, required)
      - `genres` (text array, required)
      - `coverImage` (text, optional)
      - `ratings` (jsonb, required) - Stores the 5 rating categories
      - `overallRating` (numeric, required)
      - `dateAdded` (timestamptz, required)
      - `isStandalone` (boolean, required)
      - `seriesName` (text, optional)
      - `whichWitch` (text, required)

  2. Security
    - Enable RLS on `books` table
    - Add policy for public access (since this is a personal reading tracker)
*/

-- Create books table
CREATE TABLE IF NOT EXISTS books (
  id text PRIMARY KEY,
  title text NOT NULL,
  author text NOT NULL,
  completionMonth integer NOT NULL CHECK (completionMonth >= 1 AND completionMonth <= 12),
  completionYear integer NOT NULL CHECK (completionYear >= 1900 AND completionYear <= 2100),
  genres text[] NOT NULL DEFAULT '{}',
  coverImage text,
  ratings jsonb NOT NULL DEFAULT '{}',
  overallRating numeric NOT NULL DEFAULT 0,
  dateAdded timestamptz NOT NULL DEFAULT now(),
  isStandalone boolean NOT NULL DEFAULT true,
  seriesName text,
  whichWitch text NOT NULL
);

-- Enable Row Level Security
ALTER TABLE books ENABLE ROW LEVEL SECURITY;

-- Create policy for public access (adjust as needed for your use case)
CREATE POLICY "Allow all operations on books"
  ON books
  FOR ALL
  TO public
  USING (true)
  WITH CHECK (true);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_books_dateAdded ON books(dateAdded DESC);
CREATE INDEX IF NOT EXISTS idx_books_author ON books(author);
CREATE INDEX IF NOT EXISTS idx_books_completionYear ON books(completionYear);
CREATE INDEX IF NOT EXISTS idx_books_whichWitch ON books(whichWitch);
CREATE INDEX IF NOT EXISTS idx_books_genres ON books USING GIN(genres);